version: '3.8'

services:
  pinecone:
    image: ghcr.io/pinecone-io/pinecone-local:latest
    restart: always
    environment:
      PORT: 5080
      PINECONE_HOST: localhost
    ports:
      - "5080-5090:5080-5090"
    volumes:
      - pinecone-data:/data

volumes:
  pinecone-data:
