version: '3.8'

services:
  builderapi-api:
    image: naankaran/fbrdc:dc-new
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - ./builderapi.env   # Reference to the external environment file
    ports:
      - "8080:8080"
      - "32779:443"  # Expose port 8080 of the container to port 8081 on the host
    networks:
      - backend_api_net
      - shared_internal_network

  response-api:
    image: naankaran/formresponseapidc:dc-new
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - ./responseapi.env   # Reference to the external environment file
    ports:
      - "8081:8080"  # Expose port 8080 of the container to port 8081 on the host
      - "32780:443"  
    networks:
      - backend_api_net
      - shared_internal_network
      
  master-api:
    image: naankaran/dashboard-master-apidc:dc-new
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - ./masterapi.env   # Reference to the external environment file
    ports:
      - "8082:8080"  # Expose port 8080 of the container to port 8081 on the host
      - "32781:443"
    networks:
      - backend_api_net
      - shared_internal_network

  input-api:
    image: naankaran/input-api-dc:dc-new
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - ./inputapi.env   # Reference to the external environment file
    ports:
      - "3000:3000"  # Expose port 8080 of the container to port 8081 on the host
    networks:
      - backend_api_net
      - shared_internal_network


networks:
  backend_api_net:
    driver: overlay
  shared_internal_network:
    external: true
