version: '3.8'
 
services:
  clickhouse-server:
    image: clickhouse/clickhouse-server
    container_name: clickhouse-server
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native TCP interface
    environment:
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: yourpassword
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - clickhouse_data:/var/lib/clickhouse
 
  tabix:
    image: spoonest/clickhouse-tabix-web-client
    container_name: clickhouse-tabix
    depends_on:
      - clickhouse-server
    ports:
      - "8080:80"
 
volumes:
  clickhouse_data: