version: "3.8"

services:
  grafana:
    image: grafana/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=customadmin
      - GF_SECURITY_ADMIN_PASSWORD=mynewpassword
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    depends_on:
      - loki
      - prometheus
    networks:
      - monitoring
      - shared_internal_network

  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - monitoring
      - shared_internal_network

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    networks:
      - monitoring
      - shared_internal_network

volumes:
  grafana_data:
  prometheus_data:
  loki_data:

networks:
  monitoring:
    driver: overlay
  shared_internal_network:
    external: true