version: '3.8'

services:
  formbuilder-ui:
    image: naankaran/formbuilder-ui:dc-new
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "4200:4200"
    networks:
      - shared_internal_network

      
  dashboard-ui:
    image: naankaran/dashboard-ui:dc-new
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - "4201:4201"  # Expose port 8080 of the container to port 8081 on the host
    networks:
      - shared_internal_network

networks:
  shared_internal_network:
    external: true
