version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management  # Includes the management UI
    deploy:
      mode: replicated
      replicas: 1  # Increase for clustering
      restart_policy:
        condition: on-failure
      # placement:
      #   constraints:
      #     - node.role == worker  # Run on worker nodes
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=secretpassword
      - RABBITMQ_ERLANG_COOKIE=my_secret_cluster_cookie
      - RABBITMQ_SSL_CACERTFILE=/certs/rabbitmq-cert.pem
      - RABBITMQ_SSL_CERTFILE=/certs/rabbitmq-cert.pem
      - RABBITMQ_SSL_KEYFILE=/certs/rabbitmq-key.pem
      - RABBITMQ_SSL_VERIFY=verify_none  # Disable strict certificate checking
      - RABBITMQ_SSL_FAIL_IF_NO_PEER_CERT=false
    ports:
      - "5672:5672"    # RabbitMQ main communication port
      - "15672:15672"  # RabbitMQ Management UI
      - "5671:5671"   # RabbitMQ main communication port (SSL)
      - "15671:15671" # RabbitMQ Management UI (HTTPS)
    networks:
      - shared_internal_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq  # Persistent data storage
      - ./certs:/certs:ro  # Mount SSL certificates

networks:
  shared_internal_network:
    external: true

volumes:
  rabbitmq_data:
    driver: local
