version: '3.8'

services:
  nginx:
    image: nginx:latest
    networks:
      - shared_internal_network
    volumes:
      - ./fullchain.pem:/etc/nginx/ssl/fullchain.pem
      - ./private.key:/etc/nginx/ssl/private.key
      - ../minio/fullchain.pem:/etc/nginx/ssl/minio-fullchain.pem
      - ../minio/private.key:/etc/nginx/ssl/minio-private.key
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"   # Expose NGINX on port 80
      - "443:443" # Expose NGINX on port 443
    deploy:
      mode: replicated
      replicas: 1

networks:
  shared_internal_network:
    external: true
