version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager  # Ensure Portainer runs only on manager nodes
    ports:
      - "9001:9000"  # Web UI
      - "9443:9443"  # Secure Web UI (HTTPS)
    volumes:
      - portainer_data:/data  # Persistent storage for Portainer
      - /var/run/docker.sock:/var/run/docker.sock  # Required for managing Docker

  agent:
    image: portainer/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    deploy:
      mode: global  # Runs an agent on every node in the swarm

volumes:
  portainer_data:
