version: '3.8'

services:
  vault:
    image: hashicorp/vault:latest
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_CLUSTER_ADDR: "http://0.0.0.0:8201"
    deploy:
      mode: replicated
      replicas: 1  # Increase for HA
      restart_policy:
        condition: on-failure
    volumes:
      - vault_data:/vault/file
      - ./vault-config:/vault/config 
    command: vault server -config=/vault/config/vault.hcl

volumes:
  vault_data:
