version: '3.8'

services:
  import-function:
    image: naankaran/import-function-dc:dc-new
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - ./import-function.env   # Reference to the external environment file
    networks:
      - shared_internal_network

  external-api-function:
    image: naankaran/external-api-function-dc:dc-new
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - ./external-api-function.env   # Reference to the external environment file
    networks:
      - shared_internal_network

  delete-responses-function:
    image: naankaran/delete-resposes-function-dc:dc-new
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    env_file:
      - ./delete-responses.env   # Reference to the external environment file
    networks:
      - shared_internal_network

networks:
  shared_internal_network:
    external: true
