version: '3.8'

services:
  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      # placement:
      #   constraints:
      #     - node.role == worker  # Ensure MinIO runs on a worker node
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=admin
      - MINIO_ROOT_PASSWORD=secretpassword
    networks:
      - minio_net
      - shared_internal_network
    ports:
      - "9002:9000"  # MinIO API
      - "9001:9001"  # MinIO Console

networks:
  minio_net:
    driver: overlay
  shared_internal_network:
    external: true

volumes:
  minio_data:
    driver: local
