version: '3.8'

services:
  redis:
    image: redis:latest
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      # placement:
      #   constraints:
      #     - "node.role == worker"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - redis_network
      - shared_internal_network

volumes:
  redis_data:
    driver: local

networks:
  redis_network:
    driver: overlay
  shared_internal_network:
    external: true
